### ISSUE TITLE
教師なし学習

### ISSUE THREAD

**Issue by okte2** [seinosuke/sabina#1]
素晴らしいライブラリをありがとうございます！
教師なし学習についてもシミュレーションしたいと考えているのですが、実装予定でしょうか？

**Comment by seinosuke** [comment]
本gemへのご意見、ご感想ありがとうございます。

教師なし学習の実装についてですが、
私としても現在実装されている多層パーセプトロン以外の機能も
今後充実させていきたいと考えています。

しかし、生活が忙しくなかなか時間がとれないので、
早期の対応を確約できない現状にあります。
大変申し訳ありませんが、どうか気長にお待ちください。

教師なし学習と言ってもさまざまな手法があり
ご期待に添えるものかはわかりませんが、
以前、Rubyでの教師なし学習の一例として
VBEMアルゴリズムをクラスタリングに適用したものを実装したことがあります。

詳しくは私のブログをご参照下さい。
http://syoshinsyakangeisagi.blogspot.jp/2016/09/ruby-vbemprml10.html

**Comment by okte2** [comment]
ご返信ありがとうございます！
クラスタ数を最適化してくれるのすごいですね。とても参考になります。
気長に期待してお待ちたいと思います。応援しております。

**Comment by seinosuke** [comment]
今後ともよろしくお願いいたします。
